Changes in driver adhering to New JSON API Server Spec
stargate/stargate-mongoose pull request #7
Opened 2023-01-17 22:26 UTC by kathirsvn

The JSON API server (i.e. new version of the docs server) has new http specifications as outlined here.

https://github.com/stargate/doc-api/blob/main/document-api-spec.textile
https://github.com/stargate/doc-api/blob/main/document-api-network-spec.textile

Stargate mongoose driver (forked from [stargate/stargate-mongoose](https://github.com/stargate/stargate-mongoose)) repo is being modified in this repo to adhere to the new specification.

The operations (such as insertOne, findOne, find, etc.) that are agreed for development are tracked in a 'Postman' collection here. 
https://datastax.postman.co/workspace/Stargate-Doc-API-V3-Dev~641686bd-5f9d-4def-b0f8-47fd562868ed/collection/24363330-6ec27e5b-b831-4997-89ca-34e361039d40?action=share&creator=24381626

Below are the APIs modified as per the new specification.

The old implementations of the APIs that are yet to be implemented (for example `findOneAndReplace`) have been removed, to have a clean implementation once those are agreed for development as well. 

_Note : 'deleteMany' API is yet to be implemented on the server side, and so, instead of failing, it has been set to return empty result (i.e. success) for now._

In order to run this branch locally, we need to set up `.env` file based on the `.env.example` file and I can share the postman details separately if you would like to run the tests against postman.

| API             |  
| ----------- | 
| find
| findOne
| insertOne
| insert (internally invokes insertMany)
| insertMany
| findOneAndUpdate
| deleteOne
| updateOne
| updateMany
| update (internally invokes updateMany)

2023-01-20 02:05 UTC, kidrecursive commented
Heya, this looks good, is the plan to keep it in this repo until the document API is further along in stargate?

2023-01-20 02:05 UTC, kidrecursive approved these changes

2023-01-20 03:38 UTC, amorton requested changes
Looks good, mostly nit picking and tweaks. I went through with @kidrecursive  , he had a couple of points - we have both reviewed.

2023-01-20 03:38 UTC, amorton commented on src/client/httpClient.ts
> +      //return resp;
NIT: remove old code in all places.

2023-01-20 03:38 UTC, amorton commented on src/client/httpClient.ts
> +            message: "Server call failed, please retry!"
The error message is swallowed, lets set message to be `e.message` and also add `error:e` to the object?

2023-01-20 03:38 UTC, amorton commented on src/client/httpClient.ts
> +      //console.log("URL : " + requestInfo.url);
logging should be using the `logger` imported at the top of the file and then log at the appropriate level, e.g. 

```
logger.debug(`Request url ${url}`);
```
If possible we want to avoid the string building if the debug log level is not active...

```
logger.debug("_request with URL %s", requestInfo.url);
```
Check with @kidrecursive if stuck , see https://stackoverflow.com/questions/56561576/string-interpolation-with-winston-not-working-in-nodejs

2023-01-20 03:38 UTC, amorton commented on src/collections/cursor.ts
> +//this is as in mongo shell https://www.mongodb.com/docs/v5.0/tutorial/configure-mongo-shell/#change-the-mongo-shell-batch-size
remove reference to mongo pls :)

2023-01-20 03:38 UTC, amorton commented on src/collections/cursor.ts
> +  projection: any;
nit: confusing to have projection, it's part of the query. But I now understand the query property here is only the `filter` of the query. Consider renaming `query` to be `filter` to make clearer.

2023-01-20 03:38 UTC, amorton commented on src/collections/cursor.ts
> +  constructor(collection: any, query: any, projection?: any, options?: any) {
nit: collection data type should be Collection not any

2023-01-20 03:38 UTC, amorton commented on src/collections/cursor.ts
> +    this.batchSize = options?.pageSize || DEFAULT_PAGE_SIZE;
nit: change batchSize to pageSize if they are the same thing. It should match the name used in command options.

2023-01-20 03:38 UTC, amorton commented on src/collections/cursor.ts
> +      options.pageState = this.nextPageState;
nit: use the same name for the pageState

2023-01-20 03:38 UTC, amorton commented on src/collections/db.ts
> +        .catch(err => {
Do we need to catch if we are not doing anything with the error.

2023-01-20 03:38 UTC, amorton commented on src/collections/utils.ts
>  export const formatQuery = (query: any, options?: any) => {
check if this function is still needed, it may be a hangover from the initial R&D version we made - from talking with @kidrecursive

2023-01-20 03:38 UTC, amorton commented on src/collections/utils.ts
> +  //uri.searchParams.append('baseApiPath', '/v2/namespaces');
nit: remove unused code.

2023-01-20 03:38 UTC, amorton commented on src/driver/collection.ts
> +    //return this.collection.updateMany(query, newDoc, options, cb);
what should happen here, error or call something ?

2023-01-20 03:38 UTC, amorton commented on src/driver/connection.ts
> +      /*if (!client.httpClient.isAstra) {
we can prob remove all this, the path is the old doc V2 API path

2023-01-27 15:42 UTC, kathirsvn commented
> Heya, this looks good, is the plan to keep it in this repo until the document API is further along in stargate?

Hi @kidrecursive Yes, thats correct.

2023-01-27 15:57 UTC, kathirsvn commented on src/client/httpClient.ts
> +      //return resp;
Cleaned up the code.

2023-01-27 19:53 UTC, kathirsvn commented on src/client/httpClient.ts
> +            message: "Server call failed, please retry!"
I set the message to be e.message. 

But I'm not clear on this part of the message. Could you please elaborate a little bit more on this?

> 'also add error:e to the object?'

2023-01-27 19:54 UTC, kathirsvn commented on src/client/httpClient.ts
> +      //console.log("URL : " + requestInfo.url);
Thanks for the link. Changed console.log statements to logger statements as required.

2023-01-27 19:58 UTC, kathirsvn commented on src/collections/cursor.ts
> +  projection: any;
Changed it to filter

2023-01-27 19:58 UTC, kathirsvn commented on src/collections/cursor.ts
> +  constructor(collection: any, query: any, projection?: any, options?: any) {
Done

2023-01-27 20:03 UTC, kathirsvn commented on src/collections/cursor.ts
> +    this.batchSize = options?.pageSize || DEFAULT_PAGE_SIZE;
Done

2023-01-27 20:08 UTC, kathirsvn commented on src/collections/cursor.ts
> +      options.pageState = this.nextPageState;
Changed nextPageState to pageState and made it consistent

2023-01-27 20:10 UTC, kathirsvn commented on src/collections/db.ts
> +        .catch(err => {
Makes sense. Removed the catch block. It was there earlier to catch a specific HTTP error code when the server returns a when a create collection request is received and the collection is already present. But, it's no longer the scenario with the new server.

2023-01-27 20:14 UTC, kathirsvn commented on src/collections/utils.ts
>  export const formatQuery = (query: any, options?: any) => {
Removed this function now. It's no longer needed I think. The only thing I was doing there now is to check if 'collation' is set in the options and throw an error if present. But I think, in our new implementation, server will return an error when 'collation' option is present in the request and not supported.

2023-01-27 21:50 UTC, kathirsvn commented on src/collections/utils.ts
> +  //uri.searchParams.append('baseApiPath', '/v2/namespaces');
Done

2023-01-27 21:54 UTC, kathirsvn commented on src/driver/collection.ts
> +    //return this.collection.updateMany(query, newDoc, options, cb);
Fixed this by adding an equivalent method in the internal collection.ts and invoking that from here. However, the findOneAndReplace in collection.ts is yet to be implemented since, it's not part of this iteration of the development

2023-01-27 21:55 UTC, kathirsvn commented on src/driver/connection.ts
> +      /*if (!client.httpClient.isAstra) {
Done

2023-01-27 23:19 UTC, kathirsvn commented on src/collections/cursor.ts
> +//this is as in mongo shell https://www.mongodb.com/docs/v5.0/tutorial/configure-mongo-shell/#change-the-mongo-shell-batch-size
Done

2023-01-30 17:23 UTC, vkarpov15 commented on src/collections/collection.ts
> +        return {
In Mongoose, the expectation is that `insertOne()` will throw an error if the server returned an error. So this should probably `throw`.

2023-01-30 17:23 UTC, vkarpov15 commented on src/driver/connection.ts
> -        await client.httpClient.post('/v2/schemas/namespaces', {
Is there any way for us to automatically create a keyspace before connecting? That would be very useful.

2023-01-30 21:18 UTC, kathirsvn commented on src/collections/collection.ts
> +        return {
Got it. A couple of questions.
1. Is that the expectation for all of the APIs? Can we throw a custom exception (something called `AstraException`) wrapping the error message and make it consistent across all of the APIs?
2. In which case, `acknowledged` is generally set to `false` vs throwing an error?

2023-01-30 21:23 UTC, kathirsvn commented on src/driver/connection.ts
> -        await client.httpClient.post('/v2/schemas/namespaces', {
Got it. There's no create keyspace operation allowed at this point. I added [an issue](https://github.com/stargate/sg-mongoose2/issues/11) for this to add this functionality when server side call is available.

2023-01-31 15:39 UTC, vkarpov15 commented on src/collections/collection.ts
> +        return {
1. In Mongoose 6, the expectation is that the driver layer will call the `callback()` with an error if the server threw an error. Mongoose does **not** expect the driver layer to return an object with an error description.
2. `acknowledged` is false if [write concern was disabled](https://www.mongodb.com/docs/manual/reference/method/db.collection.updateMany/#returns). In other words, if you asked the server for a "fire and forget" write where the server confirms it received the write operation, but doesn't confirm whether it persisted the write operation yet, then you'll get back `acknowledged: false`. `acknowledged: false` is not an error.

2023-01-31 15:40 UTC, vkarpov15 commented on src/driver/connection.ts
> -        await client.httpClient.post('/v2/schemas/namespaces', {
That would be great. I don't think we need to create a keyspace for Astra, but for running stargate locally that would be very helpful.

Also, what do you think about generating an auth token automatically?

2023-01-31 19:05 UTC, jeffreyscarpenter commented on src/driver/connection.ts
> -        await client.httpClient.post('/v2/schemas/namespaces', {
Would generating an auth token programmatically mean that we have to store credentials in the client like a username/password?

2023-01-31 20:21 UTC, vkarpov15 commented on src/driver/connection.ts
> -        await client.httpClient.post('/v2/schemas/namespaces', {
Yeah, in Mongoose code you typically pass database username/password to Mongoose, and Mongoose handles the auth process.

2023-02-08 20:00 UTC, kathirsvn commented on src/collections/collection.ts
> +        return {
@vkarpov15 
- I replaced all the `acknowledged: false` return statements (when there is a failure) with 'throw new Error' now. Please review and let me know if the latest change looks good with respect to error handling.
- And now I understand better on the `acknowledged` field in the response, thanks for the detailed explanation. This is going to be 'true' in our case here for all the APIs completed so far, since there is no fire and forget kind of APIs implemented so far.

2023-02-09 16:37 UTC, vkarpov15 commented on src/collections/collection.ts
> +        throw new Error(JSON.stringify(resp.errors));
It would be great to consolidate this logic somewhere, like a `handleResponse()` function that checks `if (resp.errors && resp.errors.length > 0) { throw ... }`. We will likely want to change this error handling logic based on user feedback.

I would also recommend creating a separate `StargateServerError` class, something like:

```ts
class StargateServerError extends Error {
  constructor(response) {
    super(JSON.stringify(response.errors));
    this.errors = response.errors;
  }
}
```

That provides 1) a more informative error message, and 2) gives the user access to the unstringified errors.

2023-02-09 16:37 UTC, vkarpov15 commented on src/client/httpClient.ts
> +const REQUESTED_WITH = 'astra-mongoose/0.1.0';
Aren't we calling this project stargate-mongoose?

Also, maybe pull the version number by importing `package.json`

2023-02-09 17:01 UTC, jeffreyscarpenter commented on src/client/httpClient.ts
> +const REQUESTED_WITH = 'astra-mongoose/0.1.0';
Both great ideas

2023-02-09 22:06 UTC, kathirsvn commented on src/client/httpClient.ts
> +const REQUESTED_WITH = 'astra-mongoose/0.1.0';
Fixed it to get both name and version from package.json

2023-02-09 23:56 UTC, kathirsvn commented on src/collections/collection.ts
> +        throw new Error(JSON.stringify(resp.errors));
@vkarpov15 Make sense. I created a common function to handle `errors` from server in the `httpClient.ts `itself, so we don't have to worry about error handling the individual APIs

2023-02-09 23:58 UTC, kathirsvn commented on src/collections/collection.ts
> +        throw new Error(JSON.stringify(resp.errors));
Great suggestion on letting users access unstringified errors, thank you!

2023-02-10 22:14 UTC, vkarpov15 commented on src/collections/collection.ts
> +      } as UpdateResult;
Is there any way we can avoid this `as`? Otherwise, looks good so far :+1:

2023-02-11 10:11 UTC, kathirsvn commented on src/collections/collection.ts
> +      } as UpdateResult;
@vkarpov15 I changed it now by creating required object and returning instead of creating anonymous object and typecasting wherever possible. Please review and let me know if this looks good now.

2023-02-13 20:51 UTC, kathirsvn commented
Hi @vkarpov15, does this PR look good now, are you planning for more review? Could you please approve if this looks good? I'll look for your comments if you are planning more review, we can wait, no issues. I just wanted to follow up on the approval if the review is complete.

2023-02-14 20:52 UTC, vkarpov15 approved these changes
Looks good so far. Will have to test some more as the backend gets more complete.

2023-02-14 22:21 UTC, kathirsvn commented
Thanks @vkarpov15, I'll merge this PR once @amorton also approves this.
On the testing - Makes sense, please submit Issues in this repo, if you come across any issue during testing. I have already created some issues to work as next set of items.

2023-02-15 16:33 UTC, amorton approved these changes
discussed with Kathir, sounds like everything is good to go

2023-02-15 20:07 UTC, merged