Kathirsvn/readme update
stargate/stargate-mongoose pull request #92
Opened 2023-05-04 20:37 UTC by kathirsvn

**What this PR does**:
README is updated with the latest updates to the driver

**Which issue(s) this PR fixes**:
Fixes #13 

**Checklist**
- [X] Changes manually tested
- [X] Automated Tests added/updated
- [X] Documentation added/updated
- [X] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

2023-05-04 22:52 UTC, jeffreyscarpenter approved these changes

2023-05-05 01:14 UTC, vkarpov15 requested changes
A couple of minor details, but otherwise LGTM

2023-05-05 01:14 UTC, vkarpov15 commented on README.md
> +| findOne                     | `Model.findOne(filter)` findOne doesn't take any options
findOne() does take options. `sort` for example.

2023-05-05 01:14 UTC, vkarpov15 commented on README.md
> +| findOneAndDelete            | `Model.findOneAndDelete(filter)`
Add options params to `findOneAndX()`

2023-05-05 10:34 UTC, kathirsvn commented on README.md
> +| findOne                     | `Model.findOne(filter)` findOne doesn't take any options
Fixed in [9d2336b](https://github.com/stargate/stargate-mongoose/pull/92/commits/9d2336b652f8fb9f8cf7a67dee4d49c61ba38244)

2023-05-05 10:34 UTC, kathirsvn commented on README.md
> +| findOneAndDelete            | `Model.findOneAndDelete(filter)`
Fixed in [9d2336b](https://github.com/stargate/stargate-mongoose/pull/92/commits/9d2336b652f8fb9f8cf7a67dee4d49c61ba38244)

2023-05-05 16:40 UTC, vkarpov15 approved these changes
LGTM :+1:

2023-05-08 12:27 UTC, merged